on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_calanders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version-file: .python-version

      - name: Setup Packages
        run: |
          python3 -m pip install -r requirements.txt

      - name: Update Calanders
        run: |
          bash ./scripts/update-calanders.sh timetables.index

      - name: Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: Commit
        run: |
          (git commit -m "GitHub Workflows: Dummy Commit" | grep "Changes not staged for commit") && git add .
          (git commit -m "GitHub Workflows: Update Calanders" | grep "changed") && git push
